---

name: Continuous Integration

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set (Go)
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Lint
        run: make lint

  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set (Go)
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Test
        run: make test

  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set (Go)
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Build
        run: make build

  Docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: make docker
