---

name: Publish

on:
  push:
    branches:
      - master

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: 5iMON-bot
          password: ${{ secrets.RELEASE_TOKEN }}

      - name: Publish
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/system76/oauth2-proxy:latest
